FROM node:22-alpine

ARG NODE_ENV=production
ARG PORT=80
ARG DATABASE_URL
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET
ARG JWT_ACCESS_EXPIRES_IN
ARG JWT_REFRESH_EXPIRES_IN
ARG BCRYPT_ROUNDS

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ENV JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN}
ENV JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
ENV BCRYPT_ROUNDS=${BCRYPT_ROUNDS}

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --production=false

COPY . .

RUN chmod +x scripts/start.sh

EXPOSE 80

CMD ["./scripts/start.sh"]
