FROM node:22-alpine

ARG NODE_ENV=production
ARG PORT=80
ARG DATABASE_URL
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET
ARG JWT_ACCESS_EXPIRES_IN
ARG JWT_REFRESH_EXPIRES_IN
ARG BCRYPT_ROUNDS
ARG WEBAUTHN_RP_ID
ARG WEBAUTHN_RP_NAME
ARG WEBAUTHN_ORIGIN
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL
ARG TELEGRAM_BOT_TOKEN
ARG ADMIN_API_KEY

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ENV JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN}
ENV JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
ENV BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
ENV WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID}
ENV WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME}
ENV WEBAUTHN_ORIGIN=${WEBAUTHN_ORIGIN}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV ADMIN_API_KEY=${ADMIN_API_KEY}

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --production=false

COPY . .

RUN chmod +x scripts/start.sh

EXPOSE 80

CMD ["./scripts/start.sh"]
